ak3: backend: Support for detecting treble-enabled ROMs
to-do:
* Detect devices with separate vendor but not having treble enabled

Signed-off-by: Albert I <krascgq@outlook.co.id>
Signed-off-by: Dušan Uverić <dusan.uveric9@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -222,6 +222,13 @@ do_devicecheck() {
   if [ ! "$match" ]; then
     abort " " "Unsupported device. Aborting...";
   fi;
+  if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
+    dtb=/tmp/anykernel/treble;
+	ui_print "Treble ROM detected!";
+  else
+    dtb=/tmp/anykernel/nontreble;
+	ui_print "Non-treble ROM detected!";
+  fi;
 }
 int2ver() {
   if $BB [ "$1" -eq "$1" ] 2>/dev/null; then
@@ -410,8 +417,12 @@ do_levelcheck;
 ui_print "Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 test -f tools/$CORE || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
-PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
-if [ $? != 0 ]; then
+cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
+if [ $? != "0" ]; then
+  abort "DTB append failed. Aborting...";
+fi;
+PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
+if [ $? != "0" ]; then
   abort;
 fi;
 
